version: '3.9'

services:
    dotnet-builder:
      container_name: dotnet-builder
      # for build outside
      # volumes:
      #   - outbin:/tmp/${PROJECT_NAME}/bin
      volumes:
        - app-bin:/tmp/${PROJECT_NAME}/bin/${BUILD_CONFIGURATION}/net${DOTNET_SDK_VERSION}
      build: 
        context: ./dotnet-builder
        args:
          - DOTNET_SDK_VERSION=${DOTNET_SDK_VERSION}
          - PROJECT_NAME=${PROJECT_NAME}
      stdin_open: true # docker run -i
      tty: true        # docker run -t

    dotnet-runner:
      depends_on:
        - dotnet-builder
      container_name: dotnet-runner
      volumes:
        - app-bin:/lib/${PROJECT_NAME}
      build: 
        context: ./dotnet-runner
        args:
          - DOTNET_SDK_VERSION=${DOTNET_SDK_VERSION}
          - PROJECT_NAME=${PROJECT_NAME}
      environment:
        - EXECUTABLE_NAME=${EXECUTABLE_NAME}
      ports:
        - 5000:5000
      stdin_open: true # docker run -i
      tty: true        # docker run -t

volumes:
  app-bin:
    name: app-bin

# -- For build outside
# volumes:
#   outbin:
#     driver: local
#     driver_opts:
#       o: bind
#       type: none
#       device: ./
  