version: '3.9'

services:
  dotnet-packages:
    env_file: .env
    container_name: dotnet-packages
    environment:
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORTS=${HTTPS_PORT}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERTIFICATE_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${CERTIFICATE_FULL_PATH}
    volumes:
      - dotnet-packages-storage:/var/baget
    build:
      context: ./BaGet
    networks:
      - tt-packages
    ports:
      - 9966:80
      - ${HTTPS_PORT}:443
    stdin_open: true # docker run -i
    tty: true        # docker run -t

volumes:
  dotnet-packages-storage:
    name: dotnet-packages-storage

networks:
  tt-packages:
    driver: bridge