version: '3.9'

services:
    dotnet-api-runner:
      container_name: dotnet-api-runner
      volumes:
        - app-api-bin:${APP_ROOT_DIRECTORY}
      build: 
        context: ./app-api
        args:
          - ASP_CORE_RUNTIME_VERSION=${ASP_CORE_RUNTIME_VERSION}
          - APP_ROOT_DIRECTORY=${APP_ROOT_DIRECTORY}
      environment:
        - APP_ENTRYPOINT=${APP_ENTRYPOINT}
      ports:
        - 6969:5000
      networks:
        - app-storage_tt-api
      stdin_open: true # docker run -i
      tty: true        # docker run -t

volumes:
  app-api-bin:
    name: app-api-bin

networks:
  app-storage_tt-api:
    external: true