version: '3.9'

services:
    dotnet-builder:
      container_name: dotnet-builder
      volumes:
        - app-bin:/tmp/${PROJECT_NAME}/WebAPI/bin/${BUILD_CONFIGURATION}/net${DOTNET_SDK_VERSION}
      build: 
        context: ./dotnet-builder
        args:
          - DOTNET_SDK_VERSION=${DOTNET_SDK_VERSION}
          - PROJECT_NAME=${PROJECT_NAME}
      stdin_open: true # docker run -i
      tty: true        # docker run -t

volumes:
  app-bin:
    name: app-bin