version: '3.9'

services:
  dotnet-api-builder:
    container_name: dotnet-api-builder
    volumes:
      - app-api-bin:/tmp/${API_PROJECT_NAME}/Bin/${API_BUILD_CONFIGURATION}/net${API_DOTNET_SDK_VERSION}
    build: 
      context: ./dotnet-builder
      dockerfile: BuildOnly.Dockerfile
      args:
        - DOTNET_SDK_VERSION=${API_DOTNET_SDK_VERSION}
        - PROJECT_NAME=${API_PROJECT_NAME}
    environment:
      - BUILD_CONFIGURATION=${API_BUILD_CONFIGURATION}
    stdin_open: true # docker run -i
    tty: true        # docker run -t

  dotnet-libs-builder:
    container_name: dotnet-libs-builder
    build: 
      context: ./dotnet-builder
      dockerfile: BuildAndPushNuget.Dockerfile
      args:
        - DOTNET_SDK_VERSION=${LIB_DOTNET_SDK_VERSION}
        - PROJECT_NAME=${LIB_PROJECT_NAME}
    environment:
      - BUILD_CONFIGURATION=${LIB_BUILD_CONFIGURATION}
    networks:
       - app-packages_tt-packages
    command: ["sh", "-c", "dotnet build --configuration ${LIB_BUILD_CONFIGURATION};
        ./nuget-push.sh ${LIB_BUILD_CONFIGURATION} ${DOTNET_PACKAGE_SERVER_NAME} ${DOTNET_PACKAGE_SERVER_PORT} ${DOTNET_PACKAGE_API_KEY};
        "]
    stdin_open: true # docker run -i
    tty: true        # docker run -t

  dotnet-webclient-builder:
    container_name: dotnet-webclient-builder
    depends_on:
      - dotnet-libs-builder
    volumes:
    - app-webclient-bin:/tmp/${WEBCLIENT_PROJECT_NAME}/Bin/${WEBCLIENT_BUILD_CONFIGURATION}/net${WEBCLIENT_DOTNET_SDK_VERSION}
    build: 
      context: ./dotnet-builder
      dockerfile: BuildWithLocalPackages.Dockerfile
      args:
        - DOTNET_SDK_VERSION=${WEBCLIENT_DOTNET_SDK_VERSION}
        - PROJECT_NAME=${WEBCLIENT_PROJECT_NAME}
    environment:
      - BUILD_CONFIGURATION=${WEBCLIENT_BUILD_CONFIGURATION}
    networks:
      - app-packages_tt-packages
    stdin_open: true # docker run -i
    tty: true        # docker run -t

  dotnet-auth-builder:
    container_name: dotnet-auth-builder
    depends_on:
      - dotnet-libs-builder
    volumes:
    - app-auth-bin:/tmp/${AUTH_PROJECT_NAME}/Bin/${AUTH_BUILD_CONFIGURATION}/net${AUTH_DOTNET_SDK_VERSION}
    build: 
      context: ./dotnet-builder
      dockerfile: BuildWithLocalPackages.Dockerfile
      args:
        - DOTNET_SDK_VERSION=${AUTH_DOTNET_SDK_VERSION}
        - PROJECT_NAME=${AUTH_PROJECT_NAME}
    environment:
      - BUILD_CONFIGURATION=${AUTH_BUILD_CONFIGURATION}
    networks:
      - app-packages_tt-packages
    stdin_open: true # docker run -i
    tty: true        # docker run -t

volumes:
  app-api-bin:
    name: app-api-bin
  app-webclient-bin:
    name: app-webclient-bin
  app-auth-bin:
    name: app-auth-bin

networks:
  app-packages_tt-packages:
    external: true