version: '3.9'

services:
    # dotnet-api-builder:
    #   container_name: dotnet-api-builder
    #   volumes:
    #     - app-api-bin:/tmp/${API_PROJECT_NAME}/Bin/${API_BUILD_CONFIGURATION}/net${API_DOTNET_SDK_VERSION}
    #   build: 
    #     context: ./dotnet-builder
    #     args:
    #       - DOTNET_SDK_VERSION=${API_DOTNET_SDK_VERSION}
    #       - PROJECT_NAME=${API_PROJECT_NAME}
    #   stdin_open: true # docker run -i
    #   tty: true        # docker run -t

    # dotnet-webclient-builder:
    #   container_name: dotnet-webclient-builder
    #   volumes:
    #     - app-webclient-bin:/tmp/${WEBCLIENT_PROJECT_NAME}/Bin/${WEBCLIENT_BUILD_CONFIGURATION}/net${WEBCLIENT_DOTNET_SDK_VERSION}
    #   build: 
    #     context: ./dotnet-builder
    #     args:
    #       - DOTNET_SDK_VERSION=${WEBCLIENT_DOTNET_SDK_VERSION}
    #       - PROJECT_NAME=${WEBCLIENT_PROJECT_NAME}
    #   stdin_open: true # docker run -i
    #   tty: true        # docker run -t
    
  dotnet-lib-builder:
    container_name: dotnet-webclient-builder
    build: 
      context: ./dotnet-builder
      dockerfile: Dockerfile-packages
      args:
        - DOTNET_SDK_VERSION=${LIB_DOTNET_SDK_VERSION}
        - PROJECT_NAME=${LIB_PROJECT_NAME}
    networks:
       - dotnet-package-server_tt-packages
    command: ["sh", "-c", "dotnet build;
        
        "]
    stdin_open: true # docker run -i
    tty: true        # docker run -t

# volumes:
#   app-api-bin:
#     name: app-api-bin
#   app-webclient-bin:
#     name: app-webclient-bin

networks:
  dotnet-package-server_tt-packages:
    external: true