version: '3.9'

services: 
  database:
    container_name: tt-api-db
    build: ./postgre
    volumes:
      - tt-api-storage:/var/lib/postgresql/data
    ports:
      - 9696:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - tt-api

  auth-db:
    container_name: tt-auth-db
    build: ./postgre
    volumes:
      - tt-auth-storage:/var/lib/postgresql/data
    ports:
      - 11101:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - tt-auth

volumes:
  tt-api-storage:
  tt-auth-storage:

networks:
  tt-api:
    driver: bridge
  tt-auth:
    driver: bridge